In [ ]:
import numpy as np
import itertools

In [116]:
B = np.array([
    [0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 1, 0, 0, 0],
])

c = np.ones(12, dtype=int)  # 10 entries, all 1
c[0] = 0
c[5] = 0

print(c)


[0 1 1 1 1 0 1 1 1 1 1 1]


In [117]:
B.shape

(12, 9)

In [119]:
def count_satisfied_constraints(assignment):
    """
    assignment: array-like of 4 binary variables (b1, b2, b3, b4)
    returns: number of satisfied constraints
    """
    assignment = np.array(assignment) % 2  # make sure it's mod 2
    lhs = (B @ assignment) % 2
    satisfied = (lhs == c)
    return np.sum(satisfied)

# Example usage:
assignment = np.random.randint(0, 2, size=(B.shape[1]))  # example assignment
num_satisfied = count_satisfied_constraints(assignment)
print(f"Assignment {assignment} satisfies {num_satisfied} out of {(B.shape[0])} constraints.")


Assignment [0 0 1 0 1 1 0 1 1] satisfies 4 out of 12 constraints.


In [120]:
# Enumerate all 2^4 = 16 possible assignments
all_assignments = list(itertools.product([0, 1], repeat=B.shape[1]))

# Track best assignments
best_count = -1
best_assignments = []

for assignment in all_assignments:
    count = count_satisfied_constraints(assignment)
    if count > best_count:
        best_count = count
        best_assignments = [assignment]
    elif count == best_count:
        best_assignments.append(assignment)

# Display results
print(f"Best number of satisfied constraints: {best_count} out of {(B.shape[0])}")
print("Best assignment(s):")
for assignment in best_assignments:
    print(assignment)


Best number of satisfied constraints: 12 out of 12
Best assignment(s):
(1, 0, 0, 0, 1, 0, 0, 1, 0)


In [121]:
num_nonzero = None
while(num_nonzero!=3):
    # Generate random 0-1 matrix of size 16 x 18
    B = np.random.randint(0, 2, size=(15,9))
    
    c = np.random.randint(0, 2, size=(15))
        
    # Enumerate all 2^4 = 16 possible assignments
    all_assignments = list(itertools.product([0, 1], repeat=B.shape[1]))
    
    # Track best assignments
    best_count = -1
    best_assignments = []
    
    for assignment in all_assignments:
        count = count_satisfied_constraints(assignment)
        if count > best_count:
            best_count = count
            best_assignments = [assignment]
        elif count == best_count:
            best_assignments.append(assignment)
    
    # Display results
    print(f"Best number of satisfied constraints: {best_count} out of {(B.shape[0])}")
    print("Best assignment(s):")
    for assignment in best_assignments:
        print(assignment)

    num_nonzero = np.max([np.count_nonzero(a) for a in best_assignments])
    print(num_nonzero)


Best number of satisfied constraints: 13 out of 15
Best assignment(s):
(0, 1, 0, 1, 0, 1, 0, 1, 1)
5
Best number of satisfied constraints: 13 out of 15
Best assignment(s):
(0, 1, 1, 1, 0, 1, 1, 1, 0)
(1, 1, 1, 0, 1, 0, 0, 1, 0)
6
Best number of satisfied constraints: 12 out of 15
Best assignment(s):
(0, 0, 0, 0, 1, 0, 1, 0, 1)
(0, 0, 0, 1, 1, 1, 1, 0, 1)
(1, 0, 0, 1, 1, 1, 1, 0, 1)
(1, 0, 1, 1, 0, 0, 1, 1, 1)
(1, 0, 1, 1, 0, 1, 0, 1, 1)
(1, 1, 0, 1, 0, 0, 1, 0, 0)
6
Best number of satisfied constraints: 15 out of 15
Best assignment(s):
(1, 0, 1, 1, 0, 0, 0, 0, 1)
4
Best number of satisfied constraints: 14 out of 15
Best assignment(s):
(0, 0, 1, 0, 0, 1, 0, 0, 0)
2
Best number of satisfied constraints: 14 out of 15
Best assignment(s):
(0, 0, 0, 1, 1, 1, 0, 1, 1)
5
Best number of satisfied constraints: 13 out of 15
Best assignment(s):
(0, 1, 0, 0, 1, 1, 1, 0, 0)
(1, 0, 0, 0, 0, 1, 1, 0, 0)
(1, 0, 1, 1, 0, 0, 1, 0, 1)
5
Best number of satisfied constraints: 13 out of 15
Best assignment(s)

In [39]:
from itertools import combinations

# Define B
import numpy as n

B = np.array([
    [1., 1., 0., 0., 0., 0.],
    [1., 0., 0., 0., 1., 0.],
    [0., 1., 1., 0., 0., 0.],
    [0., 0., 1., 1., 0., 0.],
    [0., 0., 0., 1., 0., 1.],
    [0., 0., 0., 0., 1., 1.]
])


# Function to compute weight (number of nonzero entries)
def weight(v):
    return np.sum(v)

# Initialize minimum weight as large
min_weight = B.shape[1] + 1

# Check all nonzero combinations of rows
for r in range(1, B.shape[0]+1):
    for rows in combinations(range(B.shape[0]), r):
        combo = np.sum(B[list(rows)], axis=0) % 2
        w = weight(combo)
        if w != 0:
            min_weight = min(min_weight, w)

print(f"The minimum distance is {min_weight}")


The minimum distance is 2.0


In [36]:
import numpy as np
from itertools import combinations

def weight(v):
    return np.sum(v)

def compute_min_distance(B):
    min_weight = B.shape[1] + 1
    for r in range(1, B.shape[0]+1):
        for rows in combinations(range(B.shape[0]), r):
            combo = np.sum(B[list(rows)], axis=0) % 2
            w = weight(combo)
            if w != 0:
                min_weight = min(min_weight, w)
    return min_weight

# Parameters
n_rows = 10  # tall
n_cols = 5
n_samples = 1000  # number of random matrices to generate

best_distance = -1
best_B = None

for _ in range(n_samples):
    B = np.random.randint(0, 2, size=(n_rows, n_cols))
    d = compute_min_distance(B)
    if d > best_distance:
        best_distance = d
        best_B = B.copy()

print(f"Best distance found: {best_distance}")
print("Matrix B with best distance:")
print(best_B)


Best distance found: 2
Matrix B with best distance:
[[0 1 0 0 1]
 [0 0 0 0 0]
 [1 1 0 0 0]
 [1 0 0 0 1]
 [0 1 1 0 0]
 [0 1 1 1 1]
 [1 1 1 1 0]
 [1 1 0 0 0]
 [1 1 1 1 0]
 [1 0 1 1 1]]


1. Given B, figure out the distance and the maximum polynomial degree that can be efficiently generated with DQI 
2. Generate the approximation ratio compare to classical algorithms (using 


In [42]:
import numpy as np
from itertools import product

def code_distance(B):
    n = B.shape[1]
    min_weight = np.inf

    # Iterate over all nonzero vectors in {0,1}^n
    for bits in product([0,1], repeat=n):
        x = np.array(bits)
        if np.any(x) and np.all(B @ x % 2 == 0):
            weight = np.sum(x)
            if weight < min_weight:
                min_weight = weight
    
    return min_weight if min_weight != np.inf else 0
